# Filterbank config
filterbank:
  stft_n_filters: 1024
  stft_kernel_size: 1024
  stft_stride: 256
masknet:
  architecture: Large-DCUNet-20
  fix_length_mode: pad
# Training config
training:
  epochs: 200
  batch_size: 2
  num_workers: 6
  early_stop: yes
  gradient_clipping: 5
  limit_train_batches: 10000
  augmentation_p: 0.5
# Optim config
optim:
  # optimizer: adamw
  lr: 0.0001
  # weight_decay: !!float 1e-5
# Data config
data:
  sample_rate: 32000
  n_src: 1
# base:
#   ckpt: exp/DCUNet_TwoNoise_ClossTalk/checkpoints/epoch=71-step=720000.ckpt



