# Filterbank config
filterbank:
  stft_n_filters: 4096
  stft_kernel_size: 4096
  stft_stride: 2048
masknet:
  architecture: DCUNet-16
  fix_length_mode: trim
# Training config
training:
  epochs: 200
  batch_size: 24
  num_workers: 12
  early_stop: yes
  gradient_clipping: 5
  limit_train_batches: 10000
  augmentation_p: 0.5
# Optim config
optim:
  # optimizer: adamw
  lr: 0.0001
  # weight_decay: !!float 1e-5
# Data config
data:
  sample_rate: 32000
  n_src: 1
  